declare module "*";

export declare const images: {
  bachelorproject_Banner_png: string;
  billythezombie_BillythezombieGame_gif: string;
  billythezombie_BillythezombieIntro_gif: string;
  billythezombie_BillythezombieUpdate_gif: string;
  catfight_CatfightGame_gif: string;
  catfight_RpshG1_png: string;
  catfight_RpshG2_png: string;
  catfight_RpshIntro_png: string;
  mhard_MhardGame_png: string;
  openglscene_OpenglScene_png: string;
  pcg_PcgGame_gif: string;
  pcg_PcgGame1_gif: string;
  pcg_PcgGame2_gif: string;
  pcg_PcgGame3_gif: string;
  pcg_PcgMenu_png: string;
  physicsengine_Physicsengine_gif: string;
  quiztrainer_quiztrainer_png: string;
  r4yl_R4ylBegin_gif: string;
  r4yl_R4ylGame_gif: string;
  r4yl_R4ylGame1_gif: string;
  r4yl_R4ylMasks_gif: string;
  r4yl_R4ylWin_gif: string;
  rasterizer_MeshMaxTimeOpti_png: string;
  rasterizer_RasterizerFlags_png: string;
  rasterizer_RenderScene_png: string;
  rasterizer_ThirdGraph_png: string;
  sga2025_SgaLab_png: string;
  sga2025_SgaLab_fire_png: string;
  sga2025_SgaLab_ItemData_png: string;
  sga2025_SgaLab_Teddy_png: string;
  sga2025_SgaLab_v1_png: string;
  sga2025_SgaLab_v2_png: string;
  sga2025_SgaLab_v3_png: string;
  sga2025_SgaLab_v4_png: string;
  synthcity_SynthCityGame_gif: string;
  synthcity_SynthCityIntro_png: string;
  synthcity_SynthCityMap_png: string;
  synthcity_SynthCityMenu_png: string;
  tothemoon_tothemoon_gif: string;
  tothemoon_ToTheMoonIntro_png: string;
};
